version: "3"

services:
  apache:
    container_name: apache
    build: 
      context: apache
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - bsl
      - bdp
      - isg
      - spectrumfibre
    networks:
      - apps_network
  bsl:
    container_name: bsl
    build:
      context: .
      dockerfile: ./apps/bsl/Dockerfile
    ports:
      - "${BSL_APP_PORT}:3000"
    environment:
      - HOSTNAME=${NEXT_PUBLIC_BASE_URL}
    networks:
      - apps_network
  bdp:
    container_name: bdp
    build:
      context: .
      dockerfile: ./apps/bdp/Dockerfile
    ports:
      - "${BDP_APP_PORT}:3000"
    environment:
      - HOSTNAME=${NEXT_PUBLIC_BASE_URL}
    networks:
      - apps_network
  isg:
    container_name: isg
    build:
      context: .
      dockerfile: ./apps/isg/Dockerfile
    ports:
      - "${ISG_APP_PORT}:3000"
    environment:
      - HOSTNAME=${NEXT_PUBLIC_BASE_URL}
    networks:
      - apps_network
  spectrumfibre:
    container_name: spectrumfibre
    build:
      context: .
      dockerfile: ./apps/spectrumfibre/Dockerfile
    ports:
      - "${SFB_APP_PORT}:3000"
    environment:
      - HOSTNAME=${NEXT_PUBLIC_BASE_URL}
    networks:
      - apps_network
 

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  apps_network:
    driver: bridge
